# aegisnet/deny.toml

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
# We allow permissive industry-standard licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
]
copyleft = "deny"
allow-osi-fsf-free = "either"

[bans]
multiple-versions = "deny" # Prevents "dependency bloat"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[output]
feature-stats = "always"